# Generated by Django 2.0.7 on 2020-06-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="type",
            field=models.CharField(
                choices=[
                    ("appetizers", "appetizers"),
                    ("treats", "treats"),
                    ("entrees", "entrees"),
                    ("drinks", "drinks"),
                ],
                max_length=60,
            ),
        ),
    ]
